### ISSUE TITLE
What does <Divider /> do?

### ISSUE THREAD

**Issue by tomByrer** [PaulieScanlon/nude-ui#1]
This is a neat editor!  I might use it for my own UI demo.

What `<Divider />` is supposed to do, only create an `<hr>`?  I'm confused why you just didn't use Markdown's `---`.  Or maybe that is you create boundaries for sections?

**Comment by PaulieScanlon** [comment]
Hey @tomByrer yeah Divider is an hr. 

This difference is Divide me is a Theme UI component and Theme UI components can be used in MDX or in Js, but It’s n both cases are linked to the style object. It’s there if you want to use it but if you’re only using markdown then the hr will do the job

**Comment by tomByrer** [comment]
Ok, thanks for your reply & your library!
